CREATE TABLE IF NOT EXISTS sonja_file_embeddings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner VARCHAR(32) NOT NULL DEFAULT 'sonja',
  file_id BIGINT UNSIGNED NULL,
  s3_key VARCHAR(1024) NULL,
  filename VARCHAR(512) NULL,
  summary LONGTEXT NULL,
  grade TINYINT UNSIGNED NULL,
  subject VARCHAR(128) NULL,
  educational TINYINT(1) NOT NULL DEFAULT 1,
  embedding_model VARCHAR(128) NOT NULL,
  embedding_dim INT UNSIGNED NOT NULL,
  embedding_json JSON NOT NULL,
  content_hash CHAR(64) NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_owner_file_model (owner, file_id, embedding_model),
  KEY idx_owner_grade_subject_edu (owner, grade, subject, educational),
  KEY idx_owner_educational (owner, educational),
  KEY idx_owner_subject (owner, subject),
  KEY idx_owner_grade (owner, grade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sonja_file_embedding_chunks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner VARCHAR(32) NOT NULL DEFAULT 'sonja',
  file_id BIGINT UNSIGNED NOT NULL,
  chunk_index INT UNSIGNED NOT NULL,
  chunk_count INT UNSIGNED NOT NULL,
  chunk_size_bytes INT UNSIGNED NOT NULL,
  s3_key VARCHAR(1024) NULL,
  filename VARCHAR(512) NULL,
  content_type VARCHAR(255) NULL,
  summary LONGTEXT NULL,
  grade TINYINT UNSIGNED NULL,
  subject VARCHAR(128) NULL,
  educational TINYINT(1) NOT NULL DEFAULT 1,
  embedding_model VARCHAR(128) NOT NULL,
  embedding_dim INT UNSIGNED NOT NULL,
  embedding_json JSON NOT NULL,
  content_hash CHAR(64) NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_owner_file_chunk_model (owner, file_id, chunk_index, embedding_model),
  KEY idx_owner_grade_subject_edu_chunk (owner, grade, subject, educational),
  KEY idx_owner_educational_chunk (owner, educational),
  KEY idx_owner_subject_chunk (owner, subject),
  KEY idx_owner_grade_chunk (owner, grade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
