services:
  mservice-file:
    container_name: ms-file
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "0.0.0.0:3224:3224"
    volumes:
      - ./data:/app/data
    networks:
      - ai-assistant-network

networks:
  ai-assistant-network:
    name: ai-assistant-network
    external: true
